name: Toxicity_Moderator
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: Ben <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  draw: ^0.0.2

dev_dependencies:
  test: ^0.12.0
